-- Generated by scripts/import-ics.mjs
-- Generated at: 2026-05-02T23:41:22.694Z
-- Rows: 59 (next 90 days)
-- Paste into Supabase SQL editor. Bypasses RLS (runs as table owner).

INSERT INTO public.events (title, description, event_type, city, event_date, event_time, location, address, price_type, price_amount, rsvp_link, image_url, status, submitter_name, submitter_email) VALUES
  ('Salsa/Bachata Saturday at Havana Club', 'Saturday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party on Saturdays featuring bachata/salsa dancing and lessons, an amazing venue filled with 300+ welcoming salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/saturdays for the latest event details!', 'social', 'boston', '2026-05-03T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-saturday-at-havana-club-2-2/2026-05-02/', NULL, 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Sunday at Havana Club', 'Bachata Sundays is Boston’s Latin Playground for social dancing on Sunday nights featuring bachata lessons and dancing, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit https://havanaclubsalsa.com/sundays for the latest details!', 'social', 'boston', '2026-05-03T23:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-sunday-at-havana-club/2026-05-03/', 'https://golatindance.com/wp-content/uploads/2023/10/havana-sunday.png', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Mondays at Havana Club', 'Bachata Mondays – are always EPIC! 
Join us (and 150+ fun dancers)! 


Bachata Mondays is Boston’s hot spot for dancing on Monday nights featuring bachata (90%) and salsa (10%) dancing, bachata lessons, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit http://havanaclubsalsa.com/mondays for the latest events details!', 'social', 'boston', '2026-05-05T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-mondays-at-havana-club/2026-05-04/', 'https://golatindance.com/wp-content/uploads/2022/12/havana-monday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Tuesdays at Havana Club', 'Salsa/Bachata Tuesdays is Boston’s hot spot for bachata and salsa dancing on Tuesday nights! Featuring bachata/salsa lessons with experienced, fun teachers and a bachata/salsa dance social at an amazing venue in a cozy, welcoming atmosphere. 
Visit http://havanaclubsalsa.com/tuesdays for the latest event details!', 'social', 'boston', '2026-05-06T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-tuesdays-at-havana-club/2026-05-05/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Room Boston', 'Your Mid-Week Break 
Social Dancing Every Wednesday starting at 9:00 pm. Dance. Mingle. Repeat. 
Bachata Room Boston is your mid-week getaway. Join us each Wednesday at La Fábrica Central in Cambridge for beginner-friendly dance lessons, followed by a social dancing party. 
Walk-ins welcome. No partner needed.', 'social', 'boston', '2026-05-07T01:00:00.000Z', NULL, 'La Fabrica Central', '450 Massachussets, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-room-boston/2026-05-06/', 'https://golatindance.com/wp-content/uploads/2022/11/313379676_665007541723336_1618937492419299458_n.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Thursdays at Havana Club', 'Bachata Thursdays is Boston’s hot spot for dancing on Thursday nights featuring: bachata (70%) and salsa (20%) dancing, beginner and intermediate level bachata lessons, an amazing venue, and a fun night of bachata and salsa goodness! 
Visit http://havanaclubsalsa.com/thursdays for the latest event details!', 'social', 'boston', '2026-05-08T00:30:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-thursdays-at-havana-club/2026-05-07/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Tambo Salsa/Bachata Social', 'One of your favorites places to dance salsa is Dante Alighieri Hall in Cambridge. All the music and friendly environment you like and want. Bring your dance shoes and get ready to dance the night away meeting new friends and having fun. 
– 8:45pm Salsa lesson
– 9:30pm – 1am Music
– Performances (on certain events)
– Cover $20 Lesson + Party, $15 Party only 
Free parking and full bar.
Please RSVP the event and INVITE YOUR friends
$5 discount for students with ID', 'social', 'boston', '2026-05-09T00:45:00.000Z', NULL, 'Dante Alighieri Society of Massachusetts', '41 Hampshire Street, Cambridge, MA 02139, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/tambo-salsa-bachata-social/2026-05-08/', NULL, 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Fridays at Havana Club', 'Friday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party featuring bachata/salsa lessons and bachata/salsa dancing, an amazing venue filled with 300+ welcoming bachata and salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/fridays for the latest events details!', 'social', 'boston', '2026-05-09T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-fridays-at-havana-club/2026-05-08/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-Club-Friday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Saturday at Havana Club', 'Saturday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party on Saturdays featuring bachata/salsa dancing and lessons, an amazing venue filled with 300+ welcoming salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/saturdays for the latest event details!', 'social', 'boston', '2026-05-10T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-saturday-at-havana-club-2-2/2026-05-09/', NULL, 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Sunday at Havana Club', 'Bachata Sundays is Boston’s Latin Playground for social dancing on Sunday nights featuring bachata lessons and dancing, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit https://havanaclubsalsa.com/sundays for the latest details!', 'social', 'boston', '2026-05-10T23:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-sunday-at-havana-club/2026-05-10/', 'https://golatindance.com/wp-content/uploads/2023/10/havana-sunday.png', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Mondays at Havana Club', 'Bachata Mondays – are always EPIC! 
Join us (and 150+ fun dancers)! 


Bachata Mondays is Boston’s hot spot for dancing on Monday nights featuring bachata (90%) and salsa (10%) dancing, bachata lessons, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit http://havanaclubsalsa.com/mondays for the latest events details!', 'social', 'boston', '2026-05-12T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-mondays-at-havana-club/2026-05-11/', 'https://golatindance.com/wp-content/uploads/2022/12/havana-monday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Tuesdays at Havana Club', 'Salsa/Bachata Tuesdays is Boston’s hot spot for bachata and salsa dancing on Tuesday nights! Featuring bachata/salsa lessons with experienced, fun teachers and a bachata/salsa dance social at an amazing venue in a cozy, welcoming atmosphere. 
Visit http://havanaclubsalsa.com/tuesdays for the latest event details!', 'social', 'boston', '2026-05-13T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-tuesdays-at-havana-club/2026-05-12/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Room Boston', 'Your Mid-Week Break 
Social Dancing Every Wednesday starting at 9:00 pm. Dance. Mingle. Repeat. 
Bachata Room Boston is your mid-week getaway. Join us each Wednesday at La Fábrica Central in Cambridge for beginner-friendly dance lessons, followed by a social dancing party. 
Walk-ins welcome. No partner needed.', 'social', 'boston', '2026-05-14T01:00:00.000Z', NULL, 'La Fabrica Central', '450 Massachussets, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-room-boston/2026-05-13/', 'https://golatindance.com/wp-content/uploads/2022/11/313379676_665007541723336_1618937492419299458_n.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Thursdays at Havana Club', 'Bachata Thursdays is Boston’s hot spot for dancing on Thursday nights featuring: bachata (70%) and salsa (20%) dancing, beginner and intermediate level bachata lessons, an amazing venue, and a fun night of bachata and salsa goodness! 
Visit http://havanaclubsalsa.com/thursdays for the latest event details!', 'social', 'boston', '2026-05-15T00:30:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-thursdays-at-havana-club/2026-05-14/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Fridays at Havana Club', 'Friday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party featuring bachata/salsa lessons and bachata/salsa dancing, an amazing venue filled with 300+ welcoming bachata and salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/fridays for the latest events details!', 'social', 'boston', '2026-05-16T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-fridays-at-havana-club/2026-05-15/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-Club-Friday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Saturday at Havana Club', 'Saturday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party on Saturdays featuring bachata/salsa dancing and lessons, an amazing venue filled with 300+ welcoming salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/saturdays for the latest event details!', 'social', 'boston', '2026-05-17T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-saturday-at-havana-club-2-2/2026-05-16/', NULL, 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Sunday at Havana Club', 'Bachata Sundays is Boston’s Latin Playground for social dancing on Sunday nights featuring bachata lessons and dancing, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit https://havanaclubsalsa.com/sundays for the latest details!', 'social', 'boston', '2026-05-17T23:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-sunday-at-havana-club/2026-05-17/', 'https://golatindance.com/wp-content/uploads/2023/10/havana-sunday.png', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Mondays at Havana Club', 'Bachata Mondays – are always EPIC! 
Join us (and 150+ fun dancers)! 


Bachata Mondays is Boston’s hot spot for dancing on Monday nights featuring bachata (90%) and salsa (10%) dancing, bachata lessons, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit http://havanaclubsalsa.com/mondays for the latest events details!', 'social', 'boston', '2026-05-19T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-mondays-at-havana-club/2026-05-18/', 'https://golatindance.com/wp-content/uploads/2022/12/havana-monday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Tuesdays at Havana Club', 'Salsa/Bachata Tuesdays is Boston’s hot spot for bachata and salsa dancing on Tuesday nights! Featuring bachata/salsa lessons with experienced, fun teachers and a bachata/salsa dance social at an amazing venue in a cozy, welcoming atmosphere. 
Visit http://havanaclubsalsa.com/tuesdays for the latest event details!', 'social', 'boston', '2026-05-20T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-tuesdays-at-havana-club/2026-05-19/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Room Boston', 'Your Mid-Week Break 
Social Dancing Every Wednesday starting at 9:00 pm. Dance. Mingle. Repeat. 
Bachata Room Boston is your mid-week getaway. Join us each Wednesday at La Fábrica Central in Cambridge for beginner-friendly dance lessons, followed by a social dancing party. 
Walk-ins welcome. No partner needed.', 'social', 'boston', '2026-05-21T01:00:00.000Z', NULL, 'La Fabrica Central', '450 Massachussets, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-room-boston/2026-05-20/', 'https://golatindance.com/wp-content/uploads/2022/11/313379676_665007541723336_1618937492419299458_n.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Thursdays at Havana Club', 'Bachata Thursdays is Boston’s hot spot for dancing on Thursday nights featuring: bachata (70%) and salsa (20%) dancing, beginner and intermediate level bachata lessons, an amazing venue, and a fun night of bachata and salsa goodness! 
Visit http://havanaclubsalsa.com/thursdays for the latest event details!', 'social', 'boston', '2026-05-22T00:30:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-thursdays-at-havana-club/2026-05-21/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Fridays at Havana Club', 'Friday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party featuring bachata/salsa lessons and bachata/salsa dancing, an amazing venue filled with 300+ welcoming bachata and salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/fridays for the latest events details!', 'social', 'boston', '2026-05-23T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-fridays-at-havana-club/2026-05-22/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-Club-Friday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Saturday at Havana Club', 'Saturday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party on Saturdays featuring bachata/salsa dancing and lessons, an amazing venue filled with 300+ welcoming salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/saturdays for the latest event details!', 'social', 'boston', '2026-05-24T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-saturday-at-havana-club-2-2/2026-05-23/', NULL, 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Sunday at Havana Club', 'Bachata Sundays is Boston’s Latin Playground for social dancing on Sunday nights featuring bachata lessons and dancing, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit https://havanaclubsalsa.com/sundays for the latest details!', 'social', 'boston', '2026-05-24T23:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-sunday-at-havana-club/2026-05-24/', 'https://golatindance.com/wp-content/uploads/2023/10/havana-sunday.png', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Mondays at Havana Club', 'Bachata Mondays – are always EPIC! 
Join us (and 150+ fun dancers)! 


Bachata Mondays is Boston’s hot spot for dancing on Monday nights featuring bachata (90%) and salsa (10%) dancing, bachata lessons, an amazing venue, and a cozy, welcoming ‘house party meets social’ atmosphere. 
Visit http://havanaclubsalsa.com/mondays for the latest events details!', 'social', 'boston', '2026-05-26T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-mondays-at-havana-club/2026-05-25/', 'https://golatindance.com/wp-content/uploads/2022/12/havana-monday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Tuesdays at Havana Club', 'Salsa/Bachata Tuesdays is Boston’s hot spot for bachata and salsa dancing on Tuesday nights! Featuring bachata/salsa lessons with experienced, fun teachers and a bachata/salsa dance social at an amazing venue in a cozy, welcoming atmosphere. 
Visit http://havanaclubsalsa.com/tuesdays for the latest event details!', 'social', 'boston', '2026-05-27T00:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-tuesdays-at-havana-club/2026-05-26/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Bachata Room Boston', 'Your Mid-Week Break 
Social Dancing Every Wednesday starting at 9:00 pm. Dance. Mingle. Repeat. 
Bachata Room Boston is your mid-week getaway. Join us each Wednesday at La Fábrica Central in Cambridge for beginner-friendly dance lessons, followed by a social dancing party. 
Walk-ins welcome. No partner needed.', 'social', 'boston', '2026-05-28T01:00:00.000Z', NULL, 'La Fabrica Central', '450 Massachussets, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/bachata-room-boston/2026-05-27/', 'https://golatindance.com/wp-content/uploads/2022/11/313379676_665007541723336_1618937492419299458_n.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Thursdays at Havana Club', 'Bachata Thursdays is Boston’s hot spot for dancing on Thursday nights featuring: bachata (70%) and salsa (20%) dancing, beginner and intermediate level bachata lessons, an amazing venue, and a fun night of bachata and salsa goodness! 
Visit http://havanaclubsalsa.com/thursdays for the latest event details!', 'social', 'boston', '2026-05-29T00:30:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-thursdays-at-havana-club/2026-05-28/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-club-thursday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Salsa/Bachata Fridays at Havana Club', 'Friday Night Bachata/Salsa is Boston’s biggest bachata/salsa dance party featuring bachata/salsa lessons and bachata/salsa dancing, an amazing venue filled with 300+ welcoming bachata and salsa dancers, an inexpensive parking garage next door, and public transport on Mass Ave. one block away! 
Visit http://havanaclubsalsa.com/fridays for the latest events details!', 'social', 'boston', '2026-05-30T01:00:00.000Z', NULL, 'Havana Club', '288 Green St, Central Sq, Cambridge, MA, 02139, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-fridays-at-havana-club/2026-05-29/', 'https://golatindance.com/wp-content/uploads/2022/11/Havana-Club-Friday.jpg', 'pending', 'ICS import (golatindance.com)', 'boston@import.local'),
  ('Latin Night at Willies Steakhouse', 'Latin Fridays and Saturdays at Willies Steakhouse at 8pm. 
Rotating DJs and bands. Visit Willies Salsa House Facebook page for band details.', 'social', 'new-york-city', '2026-05-03T00:00:00.000Z', NULL, 'Willie’s Steak House', '1832 Westchester Ave, Bronx, NY, 10472-3018, United States', NULL, NULL, 'https://golatindance.com/event/latin-night-at-willies-steakhouse-2-2-2/2026-05-02/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Live Salsa Thursday through Sunday at Gonzalez Y Gonzalez', 'LIVE Salsa Bands Thursday through Sunday
Thursdays 9:00PM & 11:00PM until 3AM w/ DJ
Fridays & Saturdays 11:00PM & 1:30AM until 3AM w/ DJ
Sundays 8:00PM until 1/2AM w/ DJ
FREE Salsa Dance Lesson | Thursdays & Sundays 8:00pm
Visit https://gygnyc.com/ for class and band details!', 'social', 'new-york-city', '2026-05-03T00:00:00.000Z', NULL, 'Gonzalez y Gonzalez', '192 Mercer Street, New York, NY 10012, New York, NY, 10012, US', NULL, NULL, 'https://golatindance.com/event/live-salsa-thursday-friday-and-saturday-at-gonzalez-y-gonzalez-2-2/2026-05-02/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Bachata Sensual NYC Social Dance', 'Welcome to our Social (Sensual, Urban and Traditional), but for special weekend, we have 2 rooms for social.
ZOUK – 2nd Saturday of the month
KIZOMBA – 4th Saturday of the month 
We host the social in our own studio, KTown Dance Studio – 38W 32nd st 4FL. Every Saturday. 
Our socials are focused on the dancers and good vibes. Most of our dancers are knowledgeable toward the Sensual Bachata technique by Korke y Judith (The couple from Spain who pioneered the technique of Bachata Sensual) and we would like to spread this Technique through NYC. 
We also play music for people who love urban and traditional. At the end, our community dance Bachata. 
We welcome everyone to our social and Enjoy free Beverages. (limited Sangria) 
Dress to Dance (DtoD)
Venmo: @Steven-halim (5525)
PYPL: @shalim83@gmail.com
Zelle: 9176645525', 'social', 'new-york-city', '2026-05-03T01:00:00.000Z', NULL, 'K Town Dance Studio', '38 West 32nd St, 4th Floor, New York, NY, 10001, United States', NULL, NULL, 'https://golatindance.com/event/bachata-sensual-social-nyc/2026-05-02/', 'https://golatindance.com/wp-content/uploads/2022/11/295319555_694737338611223_4135742329595992744_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('LATIN PARTY at Bloom', 'DJ John John presents LATIN PARTY at Bloom Botanical Bistro  | FREE ADMISSION ALL NIGHT


You are all cordially invited to join us for a LATIN PARTY at Bloom Botanical Bistro for a night filled with vibrant Latin rhythms, delicious food, and amazing company. 
Starting at 9:00 PM, this event promises an unforgettable experience as you immerse yourself in the lively atmosphere as you move to the beats of salsa, merengue, bachata, and more one of NYC’s Premier Latin DJ’s “El Boricua del Sabor” DJ John John from La Mega 97.5 ROC. 
Located at 103-19 Metropolitan Avenue in Forest Hills | Queens, Bloom Botanical Bistro is surrounded by the enchanting ambiance of our botanical paradise. Sip on refreshing cocktails, indulge in mouthwatering Latin-inspired cuisine, and let the rhythms transport you to a tropical paradise. 
Whether you’re a seasoned dancer or just looking for a fun night out, LATIN PARTY at BLOOM is the place to be. Grab your friends, put on your dancing shoes, and join us for an evening of non-stop fun and excitement. Don’t miss out on this incredible event! 
MUSIC & VIBE BY DJ JOHN JOHN from La Mega 97.5 ROC 
Time: 9:00 pm to 2:00 am 

FREE ADMISSION ALL NIGHT
FOOD AND BEVERAGES AVAILABLE FOR PURCHASE
KITCHEN OPEN TILL 11:00 PM
DINNER RESERVATIONS OF 4 OR MORE INCLUDES A COMPLIMENTARY BOTTLE OF CHAMPAGNE

For dinner reservations please call 718-880-2872 or contact DJ John John at 718-290-3400.', 'social', 'new-york-city', '2026-05-03T01:00:00.000Z', NULL, 'Bloom Botanical Bistro', '103-19 Metropolitan Ave, Queens, NY, 11375, United States', NULL, NULL, 'https://golatindance.com/event/latin-party-at-bloom-every-1st-saturday-of-the-month/2026-05-02/', 'https://golatindance.com/wp-content/uploads/2025/01/481703140_10163177860094187_8599455615932914903_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Sunday Salsa Bachata at the Rose', 'Come join us at The Rose every Sunday for our Latin night and dancing!
There will be an open level dance class (often a little footwork and then partner work in either salsa or bachata), and then a social party after.
There is a bar available to purchase drinks.', 'social', 'new-york-city', '2026-05-03T21:00:00.000Z', NULL, 'The Rose – New York', '160 West 25th Street, Manhattan, NY, United States', NULL, NULL, 'https://golatindance.com/event/sunday-salsa-bachata-at-the-rose/2026-05-03/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Jimmy Anton Social', 'Every first, third and fifth Sunday of the month.', 'social', 'new-york-city', '2026-05-03T22:00:00.000Z', NULL, 'You Should be Dancing Studios', '37 W 26th St, 2nd FL, New York, NY, 10001, United States', NULL, NULL, 'https://golatindance.com/event/jimmy-anton-social-2-2-2/2026-05-03/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Live Salsa Thursday through Sunday at Gonzalez Y Gonzalez', 'LIVE Salsa Bands Thursday through Sunday
Thursdays 9:00PM & 11:00PM until 3AM w/ DJ
Fridays & Saturdays 11:00PM & 1:30AM until 3AM w/ DJ
Sundays 8:00PM until 1/2AM w/ DJ
FREE Salsa Dance Lesson | Thursdays & Sundays 8:00pm
Visit https://gygnyc.com/ for class and band details!', 'social', 'new-york-city', '2026-05-04T00:00:00.000Z', NULL, 'Gonzalez y Gonzalez', '192 Mercer Street, New York, NY 10012, New York, NY, 10012, US', NULL, NULL, 'https://golatindance.com/event/live-salsa-thursday-friday-and-saturday-at-gonzalez-y-gonzalez-2-2/2026-05-03/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Latin Mondays NYC', 'Enjoy weekly LIMITED number of discounted tickets for Monday admission before 8pm! 
Every Monday you can pay at the door regular price if these tickets are sold out. 
Doors Open at 5pm. Happy Hour, Food & Drink Specials every Monday! 
Excellent Dinner and Dancing Experience. Dining Available and tapas menu served til 11pm (Reduced prices for Monday night dining) 
Free Salsa Dance Lesson 7pm hosted by Talia Castro-Pozo and special guests (As seen in The Today Show, Univision, Latina Magazine, etc.) 
Latin DJ’s 5pm til closing & 2 sets of weekly live music at 9pm & 11pm & Dance Shows! 
5th&Mad 
7 East 36th st. & 5th Ave. 
Doors Open 5:00pm til 1am 
Info & Dinner Reservations: Call (212) 725-2164 or Text (917) 620-3109 
Tickets $15 at the door before 7.30pm, $20 after. A limited number of Early Bird Discounted tickets through Eventbrite are available every week for admission before 8pm. 
For weekly line up of bands, DJ’s, shows & latest photos please check out our social media pages: FB & IG @latinmondaysattaj 
Please dress to impress or after work attire. 
*No refunds or cancellations .If you can’t make it pls direct message us prior to the event, and we will try to accommodate you for another day as a one time courtesy. 
Thank you for supporting live music & dancing in NYC!', 'social', 'new-york-city', '2026-05-04T21:00:00.000Z', NULL, '5th & Mad', '7 East 36th Street New York, Manhattan, 10016, United States', NULL, NULL, 'https://golatindance.com/event/latin-mondays-at-taj-3/2026-05-04/', 'https://golatindance.com/wp-content/uploads/2022/11/485084545_1753960105167227_717454669314230465_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Salsa Tuesday at Mamajuana Cafe', 'Sin salsa no hay paraiso!


EVERY Tuesday; different band.
No cover charge but food & drinks for sell.


Mamajuana Cafe Bronx
3233 East Tremont Avenue
Bronx, NY 10461


Hosted by Alex Reyes
DJ Brian Martinez', 'social', 'new-york-city', '2026-05-05T22:30:00.000Z', NULL, 'Mamajuana Cafe: The Bronx', '3233 E Tremont Ave, Bronx, NY, 10461, US', NULL, NULL, 'https://golatindance.com/event/salsa-tuesday-at-mamajuana-cafe-2-2/2026-05-05/', 'https://golatindance.com/wp-content/uploads/2022/12/594066278_10166402368765278_481758767690076588_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Salsa Bachata at The Rose', 'Come join us at The Rose every Tuesday for our Latin night of dancing!
Time: 8pm – 12:30am
There will be an open level dance class at 8:30pm (often a little footwork and then partner work in either salsa or bachata), and then a social party after.
There is a bar available to purchase drinks', 'social', 'new-york-city', '2026-05-06T00:00:00.000Z', NULL, 'The Rose – New York', '160 West 25th Street, Manhattan, NY, United States', NULL, NULL, 'https://golatindance.com/event/salsa-bachata-at-the-rose/2026-05-05/', 'https://golatindance.com/wp-content/uploads/2023/01/611696023_18151096471429907_8259196900477539051_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Mi Salsa Dura Baile in the park!', 'Join us Wednesday nights for salsa, dance, and community under the stars at Washington Square Park, NY from 6:00 PM to 9:00 PM! Let’s create a more inclusive and vibrant community together. Thank you for your support!!
#salsanight #outdoor #summer #washingtonsquarepark #danceparty #nyc #meetup #free #vibes #thingstodo #music #dance #followers #everyone #mambo #salsaon1 #salsaon2 #inclusion #diversity #eastvillage #fun #salsa #bachata #highlights #thread #follower #donate #freeclass #6PM', 'social', 'new-york-city', '2026-05-06T22:00:00.000Z', NULL, 'Washington Square Park', 'Ny, NY, 10012, United States', NULL, NULL, 'https://golatindance.com/event/mi-salsa-dura-baile-in-the-park/2026-05-06/', 'https://golatindance.com/wp-content/uploads/2026/04/26390.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Live Salsa Wednesdays at Willies Steakhouse', 'Live Salsa Wednesdays at Willies Steakhouse. Every Wednesday at 8pm. 
Rotating bands. Visit Willies Salsa House Facebook page for band details.', 'social', 'new-york-city', '2026-05-07T00:00:00.000Z', NULL, 'Willie’s Steak House', '1832 Westchester Ave, Bronx, NY, 10472-3018, United States', NULL, NULL, 'https://golatindance.com/event/live-salsa-wednesdays-at-willies-steakhouse/2026-05-06/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Baila Wednesdays at Solas', 'Weds Nights Latin Music Dance Party: Baila, NYC
Every Weds 8P Class w/ Social Dance Party, 9p- 1a
@ Solas Bar Lounge, 232 E. 9th st NYC.
2 Rooms of Music:
General Admission: $15
Dance Class includes party admission.
**********************************
Baila Weds is a long running latin music dance party on NYC’s East Village-NYU District. A night of Salsa, Mambo, World Latin & Bachata Beats, always featuring new & classic music from Latin Music Diaspora.', 'social', 'new-york-city', '2026-05-07T00:00:00.000Z', NULL, 'Solas Bar NYC', '232 E 9th St # 1, New York, NY, 10003, United States', NULL, NULL, 'https://golatindance.com/event/baila-wednesday-solas-new-york-city/2026-05-06/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Roofchata Wednesdays', ' From 9 pm – 1 am⁠
 9 PM FREE BACHATA CLASS
 $15 all night⁠
 230 Fifth: Best Rooftop Bar/Club/Restaurant In NYC!!!', 'social', 'new-york-city', '2026-05-07T01:00:00.000Z', NULL, '230 5th Ave', '230 5th Avenue, New York, NY, 10001, United States', NULL, NULL, 'https://golatindance.com/event/roofchata-wednesdays/2026-05-06/', 'https://golatindance.com/wp-content/uploads/2022/11/315556325_2985288538434607_4788761746463227878_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Salsa Thursdays at Time Out Market', 'Join us for one of NYC’s best free salsa nights and turn your Thursday into a dance-floor celebration.


Get your salsa on every Thursday night at Time Out Market New York! Head up to the fifth floor for an electrifying evening of rhythm, movement, and Latin vibes. Whether you’re a total beginner or a seasoned dancer, this is your weekly excuse to move, sweat, and smile. 
Starting at 7:30 PM, renowned instructor Marlene Veras will guide you through the steps, breaking down the fundamentals so you feel confident on the dance floor. The night is powered by infectious beats from DJ Ray Suave, with live percussion by Jessica La Timbalera, setting the stage for a high-energy salsa experience. 
After the lesson, the floor opens up for a full-on salsa dance party until 10 PM. Bring a partner or come solo—everyone’s welcome.', 'social', 'new-york-city', '2026-05-07T23:00:00.000Z', NULL, 'Time Out Market New York', '55 Water Street DUMBO, Brooklyn, NY 11201, Brooklyn, NY, 11201, US', NULL, NULL, 'https://golatindance.com/event/salsa-thursdays-at-time-out-market/2026-05-07/', 'https://golatindance.com/wp-content/uploads/2026/02/301028_image.png', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Passion Thursdays at SOLAS Bar & Lounge', 'Yes, we are bringing you some BACHATA to the middle of your week!! Every Thursday we bring you some of the best latin dancing in the Lower East Side! 
We play that Sensual • Modern • Traditional Bachata with a splash of Salsa & Merengue mixes. 
$6 drink specials ALL NIGHT!!!
Doors open 7pm // Complimentary Bachata lesson @8pm', 'social', 'new-york-city', '2026-05-07T23:00:00.000Z', NULL, 'Solas', '232 East 9th Street ## 1, New York, NY 10003, New York, NY, 10003, US', NULL, NULL, 'https://golatindance.com/event/passion-thursdays-at-solas-bar-lounge/2026-05-07/', 'https://golatindance.com/wp-content/uploads/2021/06/612346785_1540678031010405_7816403640636041549_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Baila at High Bar', 'Salsa on the rooftop! 8-11pm: Son, Guaracha, Mambo, Songo, Timba, Bachata…', 'social', 'new-york-city', '2026-05-08T00:00:00.000Z', NULL, 'High Bar New York', '346 W 40th St, New York, NY, 10018, United States', NULL, NULL, 'https://golatindance.com/event/baila-at-high-bar/2026-05-07/', 'https://golatindance.com/wp-content/uploads/2025/07/611249897_886891283991203_287031588821694085_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Live Salsa Thursday through Sunday at Gonzalez Y Gonzalez', 'LIVE Salsa Bands Thursday through Sunday
Thursdays 9:00PM & 11:00PM until 3AM w/ DJ
Fridays & Saturdays 11:00PM & 1:30AM until 3AM w/ DJ
Sundays 8:00PM until 1/2AM w/ DJ
FREE Salsa Dance Lesson | Thursdays & Sundays 8:00pm
Visit https://gygnyc.com/ for class and band details!', 'social', 'new-york-city', '2026-05-08T00:00:00.000Z', NULL, 'Gonzalez y Gonzalez', '192 Mercer Street, New York, NY 10012, New York, NY, 10012, US', NULL, NULL, 'https://golatindance.com/event/live-salsa-thursday-friday-and-saturday-at-gonzalez-y-gonzalez-2-2/2026-05-07/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('CLASICOS THURSDAYS at D''Antigua', 'Hola mi gente, 
I would like to cordially invite you to CLASICOS THURSDAYS at the legendary D’Antigua at 84-16 Northern Blvd in Jackson Heights/Queens every Thursday as we feature the best in salsa classics in vinyl from the best DJ’s around including your host “El Boricua del Sabor” DJ John John. 
We open doors at 9 pm with a complimentary salsa class to get you started and then go straight into dance mode at this beautiful, elegant, and spacious venue that also offers a Full bar with Happy Hour All Night and a delicious food menu. 
Happy Hour: $5 Beers | $6 Wines | $7 Micheladas | $8 Sangria & Well Drinks 
Cover: JUST $10 ALL NIGHT 
Venue: 
D’Antigua 
84-16 Nothern Blvd 
Jackson Heights, NY 11372 
Dinner/Table RSVP: (718) 779-0128 
 ', 'social', 'new-york-city', '2026-05-08T01:00:00.000Z', NULL, 'D’antigua', '84-16 Nothern Blvd, Jackson Heights, Queens, NY, 11372, United States', NULL, NULL, 'https://golatindance.com/event/clasicos-thursdays-at-dantigua-every-1st-3rd-thursday-of-the-month/2026-05-07/', 'https://golatindance.com/wp-content/uploads/2025/12/613587433_1456527036481886_1083403841486279672_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Bachateame Thursday', 'Every Thursday is Bachatéame Thursday at Puerto Plata Seafood & Billiards with NO COVER CHARGE. Enjoy a live performance by Savi Rodriguez and music by DJ Doble AA. Party from 9 PM to 2 AM with amazing drink and bottle specials. Kitchen remains open until 1 AM.', 'social', 'new-york-city', '2026-05-08T01:00:00.000Z', NULL, 'Puerto Plata – Queens', '7516 Rockaway Blvd, Queens, NY, 11421, United States', NULL, NULL, 'https://golatindance.com/event/bachateame-thursday/2026-05-07/', 'https://golatindance.com/wp-content/uploads/2026/02/629214336_10225928500673992_4147955267839922150_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Latin Night at Willies Steakhouse', 'Latin Fridays and Saturdays at Willies Steakhouse at 8pm. 
Rotating DJs and bands. Visit Willies Salsa House Facebook page for band details.', 'social', 'new-york-city', '2026-05-09T00:00:00.000Z', NULL, 'Willie’s Steak House', '1832 Westchester Ave, Bronx, NY, 10472-3018, United States', NULL, NULL, 'https://golatindance.com/event/latin-night-at-willies-steakhouse-2-2-2/2026-05-08/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Salsa on the Rooftop: Latin Night at Elsie Rooftop', 'Join us for a night of dancing under the stars with a live band playing the hottest Latin tunes – Salsa In The Sky!


Welcome to Salsa on the Roof!
Come join us for a night of spicy Latin dancing under the stars at Elsie Rooftop. 
Get ready to move your hips to the rhythm of a live band Grupo Tahona playing all your favorite Latin tunes. 
Grab your dancing shoes and get ready for a night of Latin Music like you’ve never experienced before. Whether you’re a seasoned pro or a beginner, this event is perfect for anyone looking to have a great time and meet new people. Don’t miss out on the chance to dance the night away in a stunning rooftop setting! 
*VIP Tickets include: 1- hour Salsa Class led by Valerie Levine and Talia Castro-Pozo, and a 1 hour open bar from 8pm – 9pm. 
*GA Includes: Entry to the event after 9pm 
Hosted By Talia Castro-Pozo and Valerie Levine 
Live Band From 9:30pm – 12:30am 
DJ All Night 
Pitchers of Sangria, Mojito, and Margaritas for $49 
*For tables of 4 or more please email info@elsierooftop.com 
Talia Castro-Pozo Bio: A linchpin in sustaining New York City’s vibrant Latin culture for over 16 years, Talia Castro-Pozo shines as the creative force behind celebrated events like Latin Mondays at Taj, the Bryant Park Dance Party, and Hudson River Park’s Sunset Salsa, among others. Her engaging, warm, and inclusive style has been instrumental in igniting a passion for Latin dance and culture within the hearts of New Yorkers. An accomplished dancer, actress, and choreographer, Talia has been a prominent figure in numerous commercials both in the U.S. and internationally, alongside appearances in films and TV shows. Recognized as a spokesperson and an expert in Latin dance, she has been captivating audiences with her performances since she was four years old. 
Valerie Levine Bio: Valerie Levine is a distinguished dancer and skater who has made New York City her stage, teaching and performing across the city and beyond. She is the visionary founder of Valerina Dance, a performance company that showcases an eclectic mix of Belly Dancing, Brazilian Samba, Flamenco, Ballroom/Latin dances, figure skating, roller skating, and synthetic ice shows. Her artistic journey has taken her to remarkable destinations such as Cairo, Egypt; Guatemala; and Lake Como, Italy, where she has shared her talent and passion for dance. 
Grupo Tahona Bio: Emerging from New York City, under the leadership of Luis Córdoba, Grupo Tahona is a dynamic ensemble known for its original salsa compositions including hits like “Tahona,” “Joe Pa Ti,” “Yroco,” “Canconito,” and “Joey,” brought to life under the musical direction of Jose Mangual Jr. and Luis Cordoba. In 2022, their innovative sound earned them a nomination for the prestigious Premios Cristo Rey as the best Salsa group in Colombia, marking them as influential contributors to the global salsa music scene. 
 ', 'social', 'new-york-city', '2026-05-09T00:00:00.000Z', NULL, 'Elsie Rooftop', '1412 Broadway, Manhattan, New York, NY, 10018, United States', NULL, NULL, 'https://golatindance.com/event/salsa-on-the-rooftop-latin-night-at-elsie-rooftop/2026-05-08/', 'https://golatindance.com/wp-content/uploads/2025/03/264531_image-scaled.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Live Salsa Thursday through Sunday at Gonzalez Y Gonzalez', 'LIVE Salsa Bands Thursday through Sunday
Thursdays 9:00PM & 11:00PM until 3AM w/ DJ
Fridays & Saturdays 11:00PM & 1:30AM until 3AM w/ DJ
Sundays 8:00PM until 1/2AM w/ DJ
FREE Salsa Dance Lesson | Thursdays & Sundays 8:00pm
Visit https://gygnyc.com/ for class and band details!', 'social', 'new-york-city', '2026-05-09T00:00:00.000Z', NULL, 'Gonzalez y Gonzalez', '192 Mercer Street, New York, NY 10012, New York, NY, 10012, US', NULL, NULL, 'https://golatindance.com/event/live-salsa-thursday-friday-and-saturday-at-gonzalez-y-gonzalez-2-2/2026-05-08/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Socials at Lorenz Dance Studio - Nassau', '9:00PM-12:00AM 
Friday Night 
Latin Social 
Every Friday 
Please check Events Page for any closures.', 'social', 'new-york-city', '2026-05-09T01:00:00.000Z', NULL, 'Lorenz Latin Dance Studio – Nassau', '246-14 Jericho Turnpike, Queens, Floral Park, NY, 11001, United States', NULL, NULL, 'https://golatindance.com/event/socials-at-lorenz-dance-studio-nassau/2026-05-08/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Socials at Lorenz Dance Studio - Glendale', 'Every Friday 9pm-12am
$10 for Registered Studio Student
$15 for Non-Members 
Please check Events Page for any closures', 'social', 'new-york-city', '2026-05-09T01:00:00.000Z', NULL, 'Lorenz Latin Dance Studio – Glendale', '65-52 Myrtle Avenue, Queens, Glendale, NY, 11385, United States', NULL, NULL, 'https://golatindance.com/event/socials-at-lorenz-dance-studio-glendale/2026-05-08/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('FIESTA FRIDAYS at DRAMMA NIGHT CLUB (Times Square)', 'FIESTA FRIDAYS is coming to the bright lights of Times Square  at DRAMMA NIGHT CLUB featuring Salsa, Bachata & More.


Hola mi gente, 
It is with great excitement that I announce the launch of FIESTA FRIDAYS at DRAMMA NIGHT CLUB , starting February 6th. 
We kick things off at 9:00 pm with a fun and engaging complimentary salsa class at 9:15 pm with today’s top instructors to get you in the groove. 
After that, it’s all about dancing the night away with NYC’s Premier Latin DJs, including your host, “El Boricua del Sabor” DJ John John. We’ll be spinning the hottest salsa, bachata, merengue, and reggaeton hits from yesterday and today. 
This weekly event is crafted for those who love to dress up, enjoy the nightlife, and immerse themselves in an evening of dancing, cocktails, and mingling. It’s a perfect occasion to meet new people or catch up with friends without the constant partner-switching of marathon socials. 
So, spread the word far and wide – FIESTA FRIDAYS at DRAMMA is bringing back that Old School Latin Club Vibe reminiscent of the days of LQ’s and The Original Copa. 
Mark your calendars for Friday, February 6th, and ask your friends – are you going to DRAMMA? 
Date(s): 

Grand Opening Friday, February 6th
Each and every Friday thereafter

Time: 9:00 pm to 2:00 am+ 
Music by “El Boricua del Sabor” DJ John John 
Event details: 

21+ Id required
Full bar and food available


$20 in advance (Ends midnight Thursdays)
$25 thereafter and at the door
$30 VIP Seating
$5 discount at the door if you show you follow @djjohnjohnacevedo on Instagram

Advance Payment options: 

Zelle 718-290-3400
Venmo @dj-john-john-acevedo
Cashapp $djjohnjohnacevedo
PayPal johnny.acevedo@outlook.com

Venue: 
DRAMMA NIGHT CLUB 
1604 Broadway(2nd Floor) 
New York, NY 10019 
Trains: 

N, Q, R, W to 49th Street
1, 2 to 50th Street
A, C, E to 50th Street
B, D, F, M to 47-50 St/Rockafeller Center

For more information and VIP tables you can contact DJ John John at 718-290-3400.', 'social', 'new-york-city', '2026-05-09T01:00:00.000Z', NULL, 'DRAMMA TIMES SQUARE', '1604 Broadway #2nd Floor, New York, NY 10019, New York, NY, 10019, US', NULL, NULL, 'https://golatindance.com/event/fiesta-fridays-at-dramma-night-club-times-square-grand-opening-feb-6th/2026-05-08/', 'https://golatindance.com/wp-content/uploads/2026/02/https___cdn.evbuc_.com_images_1174315276_143077099654_1_original.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Sensual Bachata Fridays by Sensual Movement', 'The Sensual Movement Family is excited to announce Sensual Bachata Nights Social!
Complimentary classes from 9 pm – 10 pm ⁠
⁠From 9 PM – 2:30 AM⁠ | 9 PM Classes – 10 PM Party⁠', 'social', 'new-york-city', '2026-05-09T01:00:00.000Z', NULL, '224 W 35th St', '224 W 35th St, New York, NY, 10001-2501, United States', NULL, NULL, 'https://golatindance.com/event/sensual-bachata-fridays-by-sensual-movement-2-4/2026-05-08/', 'https://golatindance.com/wp-content/uploads/2022/12/Friday_social_20_25-819x1024-1.jpeg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Latin Night at Willies Steakhouse', 'Latin Fridays and Saturdays at Willies Steakhouse at 8pm. 
Rotating DJs and bands. Visit Willies Salsa House Facebook page for band details.', 'social', 'new-york-city', '2026-05-10T00:00:00.000Z', NULL, 'Willie’s Steak House', '1832 Westchester Ave, Bronx, NY, 10472-3018, United States', NULL, NULL, 'https://golatindance.com/event/latin-night-at-willies-steakhouse-2-2-2/2026-05-09/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Live Salsa Thursday through Sunday at Gonzalez Y Gonzalez', 'LIVE Salsa Bands Thursday through Sunday
Thursdays 9:00PM & 11:00PM until 3AM w/ DJ
Fridays & Saturdays 11:00PM & 1:30AM until 3AM w/ DJ
Sundays 8:00PM until 1/2AM w/ DJ
FREE Salsa Dance Lesson | Thursdays & Sundays 8:00pm
Visit https://gygnyc.com/ for class and band details!', 'social', 'new-york-city', '2026-05-10T00:00:00.000Z', NULL, 'Gonzalez y Gonzalez', '192 Mercer Street, New York, NY 10012, New York, NY, 10012, US', NULL, NULL, 'https://golatindance.com/event/live-salsa-thursday-friday-and-saturday-at-gonzalez-y-gonzalez-2-2/2026-05-09/', NULL, 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local'),
  ('Bachata Sensual NYC Social Dance', 'Welcome to our Social (Sensual, Urban and Traditional), but for special weekend, we have 2 rooms for social.
ZOUK – 2nd Saturday of the month
KIZOMBA – 4th Saturday of the month 
We host the social in our own studio, KTown Dance Studio – 38W 32nd st 4FL. Every Saturday. 
Our socials are focused on the dancers and good vibes. Most of our dancers are knowledgeable toward the Sensual Bachata technique by Korke y Judith (The couple from Spain who pioneered the technique of Bachata Sensual) and we would like to spread this Technique through NYC. 
We also play music for people who love urban and traditional. At the end, our community dance Bachata. 
We welcome everyone to our social and Enjoy free Beverages. (limited Sangria) 
Dress to Dance (DtoD)
Venmo: @Steven-halim (5525)
PYPL: @shalim83@gmail.com
Zelle: 9176645525', 'social', 'new-york-city', '2026-05-10T01:00:00.000Z', NULL, 'K Town Dance Studio', '38 West 32nd St, 4th Floor, New York, NY, 10001, United States', NULL, NULL, 'https://golatindance.com/event/bachata-sensual-social-nyc/2026-05-09/', 'https://golatindance.com/wp-content/uploads/2022/11/295319555_694737338611223_4135742329595992744_n.jpg', 'pending', 'ICS import (golatindance.com)', 'new-york-city@import.local');
