#!/usr/bin/env node
/**
 * Importer: scrape golatindance.com ICS feeds → Supabase events table.
 *
 * Usage:
 *   node scripts/import-ics.mjs                      # dry run (prints sample)
 *   node scripts/import-ics.mjs --insert             # writes via supabase-js (subject to RLS)
 *   node scripts/import-ics.mjs --sql                # emits INSERT SQL to stdout
 *   node scripts/import-ics.mjs --sql --days=90      # emits SQL for next 90 days only
 *   node scripts/import-ics.mjs --sql > seed.sql     # save to a file
 *
 * --sql is the recommended path right now: paste the output into the Supabase
 * SQL editor. SQL editor queries run as the table owner so RLS doesn't apply,
 * which sidesteps any policy / PostgREST cache issues.
 *
 * Reads VITE_SUPABASE_URL + VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY from .env
 * (only required for --insert; --sql mode needs no Supabase credentials).
 */

import { readFileSync, existsSync } from "node:fs";
import ICAL from "ical.js";
import { createClient } from "@supabase/supabase-js";

const FEEDS = {
  boston:
    "https://golatindance.com/events/category/boston/?post_type=tribe_events&ical=1&eventDisplay=list",
  "new-york-city":
    "https://golatindance.com/events/category/new-york-city/?post_type=tribe_events&ical=1&eventDisplay=list",
};

const SOURCE_TAG = "ICS import (golatindance.com)";

// --- Args
const args = process.argv.slice(2);
const DO_INSERT = args.includes("--insert");
const EMIT_SQL = args.includes("--sql");
const daysArg = args.find((a) => a.startsWith("--days="));
const DAYS = daysArg ? parseInt(daysArg.split("=")[1], 10) : null;

// --- .env loader (no dotenv dep)
function loadEnv() {
  const file = existsSync(".env.local")
    ? ".env.local"
    : existsSync(".env")
      ? ".env"
      : null;
  if (!file) return {};
  const out = {};
  for (const line of readFileSync(file, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/i);
    if (!m) continue;
    out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

const env = { ...loadEnv(), ...process.env };
const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_KEY = env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY;

// --- Mapping helpers
function inferEventType(title) {
  const t = title.toLowerCase();
  if (/\b(workshop|bootcamp|intensive)\b/.test(t)) return "workshop";
  if (/\b(class|lesson|crash course)\b/.test(t)) return "class";
  return "social";
}

function readString(vevent, name) {
  const v = vevent.getFirstPropertyValue(name);
  if (v === null || v === undefined) return null;
  return typeof v === "string" ? v : String(v);
}

function splitVenueAndAddress(loc) {
  if (!loc) return { location: null, address: null };
  const parts = loc.split(",").map((s) => s.trim());
  if (parts.length <= 1) return { location: null, address: loc };
  return { location: parts[0], address: parts.slice(1).join(", ") };
}

function veventToRow(vevent, city) {
  const ev = new ICAL.Event(vevent);
  const startIso = ev.startDate.toJSDate().toISOString();
  const title = ev.summary || "Untitled event";
  const { location, address } = splitVenueAndAddress(readString(vevent, "location"));

  return {
    title,
    description: readString(vevent, "description"),
    event_type: inferEventType(title),
    city,
    event_date: startIso,
    event_time: null,
    location,
    address,
    price_type: null,
    price_amount: null,
    rsvp_link: readString(vevent, "url"),
    image_url: readString(vevent, "attach"),
    status: "pending",
    submitter_name: SOURCE_TAG,
    submitter_email: `${city}@import.local`,
  };
}

// --- Fetch + parse one feed
async function fetchFeed(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`Feed ${url} → HTTP ${r.status}`);
  const text = await r.text();
  const comp = new ICAL.Component(ICAL.parse(text));
  return comp.getAllSubcomponents("vevent");
}

// --- Date filter
function withinNextDays(row, days) {
  if (days == null) return true;
  const eventTime = new Date(row.event_date).getTime();
  const now = Date.now();
  const cutoff = now + days * 24 * 60 * 60 * 1000;
  return eventTime >= now && eventTime <= cutoff;
}

// --- SQL emission
function sqlValue(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "TRUE" : "FALSE";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

const COLUMNS = [
  "title",
  "description",
  "event_type",
  "city",
  "event_date",
  "event_time",
  "location",
  "address",
  "price_type",
  "price_amount",
  "rsvp_link",
  "image_url",
  "status",
  "submitter_name",
  "submitter_email",
];

function emitSql(rows) {
  const lines = [];
  lines.push("-- Generated by scripts/import-ics.mjs");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Rows: ${rows.length}${DAYS != null ? ` (next ${DAYS} days)` : ""}`);
  lines.push("-- Paste into Supabase SQL editor. Bypasses RLS (runs as table owner).");
  lines.push("");
  lines.push(`INSERT INTO public.events (${COLUMNS.join(", ")}) VALUES`);
  const valueLines = rows.map((row, i) => {
    const vals = COLUMNS.map((c) => sqlValue(row[c])).join(", ");
    const sep = i < rows.length - 1 ? "," : ";";
    return `  (${vals})${sep}`;
  });
  lines.push(...valueLines);
  return lines.join("\n");
}

// --- Main
async function main() {
  // Validate creds only when actually inserting via supabase-js
  if (DO_INSERT && (!SUPABASE_URL || !SUPABASE_KEY)) {
    console.error(
      "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY (checked .env.local, .env, and process env)"
    );
    process.exit(1);
  }

  if (!EMIT_SQL) {
    console.log(DO_INSERT ? "Mode: INSERT" : "Mode: DRY RUN (pass --insert to write, or --sql for SQL output)");
  }

  const rows = [];
  for (const [city, url] of Object.entries(FEEDS)) {
    if (!EMIT_SQL) process.stdout.write(`Fetching ${city}... `);
    const vevents = await fetchFeed(url);
    if (!EMIT_SQL) console.log(`${vevents.length} events`);
    for (const v of vevents) rows.push(veventToRow(v, city));
  }

  const filtered = rows.filter((r) => withinNextDays(r, DAYS));

  if (!EMIT_SQL) {
    console.log(`\nFetched ${rows.length} total`);
    if (DAYS != null) {
      console.log(`Within next ${DAYS} days: ${filtered.length}`);
    }
  }

  // --sql mode: emit and exit
  if (EMIT_SQL) {
    process.stdout.write(emitSql(filtered) + "\n");
    return;
  }

  // --insert / dry-run mode below
  if (filtered.length === 0) {
    console.log("Nothing to do.");
    return;
  }

  if (!DO_INSERT) {
    console.log("\n--- Sample (first 2) ---");
    console.log(JSON.stringify(filtered.slice(0, 2), null, 2));
    console.log(`\nDry run complete. Re-run with --insert (via API) or --sql (for SQL editor).`);
    return;
  }

  // --insert path: best-effort dedup + insert via supabase-js
  const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

  const { data: existing, error: readErr } = await supabase
    .from("events")
    .select("title, event_date");

  if (readErr) {
    console.warn(`(dedup read failed: ${readErr.message} — proceeding without dedup)`);
  }

  const seen = new Set((existing ?? []).map((e) => `${e.title}|${e.event_date}`));
  const toInsert = filtered.filter((r) => !seen.has(`${r.title}|${r.event_date}`));

  console.log(`Already in Supabase: ${filtered.length - toInsert.length}`);
  console.log(`To insert: ${toInsert.length}`);

  if (toInsert.length === 0) {
    console.log("Nothing to do.");
    return;
  }

  console.log("\nInserting (status=pending)...");
  const { data, error } = await supabase.from("events").insert(toInsert).select("id");

  if (error) {
    console.error("Insert failed:", error.message);
    process.exit(1);
  }
  console.log(`✓ Inserted ${data.length} rows.`);
  console.log("Review them in Supabase and flip status='approved' to publish.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
